# Generated by Django 4.2.2 on 2023-06-29 09:33

import apps.website.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(
                        upload_to=apps.website.models.team_foto_file_path
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        default="member",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="employees",
                        to="website.role",
                    ),
                ),
            ],
        ),
    ]
