# Generated by Django 4.2.2 on 2023-07-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_job_slug_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(),
        ),
    ]
