# Generated by Django 4.2.2 on 2023-07-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailForPostNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
