# Generated by Django 4.2.2 on 2023-07-12 20:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_emailforpostnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestFromUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("question", models.TextField()),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
