# Generated by Django 4.2.2 on 2023-07-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_requestfromuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("company", models.CharField(max_length=255)),
                ("briefing", models.TextField()),
                ("result", models.TextField()),
                (
                    "cover",
                    models.ImageField(
                        upload_to="uploads/team/<function image_file_path at 0x1032544a0>"
                    ),
                ),
            ],
        ),
    ]
