# Generated by Django 4.2.2 on 2023-07-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_alter_case_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="slug",
            field=models.SlugField(default="default_slug"),
        ),
    ]
