# Generated by Django 4.2.2 on 2023-07-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_webapp_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="product",
            field=models.ForeignKey(
                default="default",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cases",
                to="website.product",
            ),
        ),
    ]
